### ISSUE TITLE
Roadmap grammY 2.0

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/grammY#675]
The following is a tentative list of issues that would  be cool to include in the next major release of grammY.

After 4 years of development without a major version, the grammY core library has accumulated a number of oddities that can only be fixed by doing breaking changes. grammY 2.0 is our opportunity to introduce these changes.

We may add or remove issues from the list below if we think that this makes sense.

There is no ETA. The release will happen when we have reached high quality. It goes faster if you contribute.

**Comment by KnorpelSenf** [comment]
Beta versions are now available on JSR: https://jsr.io/@grammyjs/grammy/versions

**Comment by KnorpelSenf** [comment]
The actual 2.0 release (whenever that happens) will be made available on npm, but the beta releases are going to be JSR-only for a while. You can install it using the npm CLI: `npx jsr add @grammyjs/grammy@2.0.0-beta.3`

**Comment by roziscoding** [comment]
# Plugin Compatibility Checklist

- [ ] [Conversations](https://github.com/grammyjs/conversations/issues/153)
- [ ] [Interactive Menus](https://github.com/grammyjs/menu/issues/63)
- [ ] [Stateless Question](https://github.com/grammyjs/stateless-question/issues/93)
- [ ] [Concurrency](https://github.com/grammyjs/runner/issues/28)
- [ ] [Hydration](https://github.com/grammyjs/hydrate/issues/32)
- [ ] [Retry API Requests](https://github.com/grammyjs/auto-retry/issues/24)
- [ ] [Rate Limit Users](https://github.com/grammyjs/ratelimiter/issues/16) (@Amir-Zouerami)
- [ ] [Files](https://github.com/grammyjs/files/issues/19)
- [ ] [Internationalization (i18n)](https://github.com/grammyjs/i18n/issues/62)
- [ ] [Router](https://github.com/grammyjs/router/issues/7)
- [ ] [Emoji](https://github.com/grammyjs/emoji/issues/24)
- [ ] [Streaming Message Drafts](https://github.com/grammyjs/stream/issues/5)
- [ ] [Chat Members](https://github.com/grammyjs/chat-members/issues/15) (@roziscoding)
- [ ] [Commands](https://github.com/grammyjs/commands/issues/84) (@carafelix)
- [ ] [Format](https://github.com/grammyjs/format/issues/1)
- [x] Parse Mode
- [ ] Sessions

---

The following plugins are being deprecated instead of migrated:

- Internationalization (fluent)
- Flood Control

If you have a use case for migrating one of them, come talk to us in the [group chat](https://t.me/grammyjs).
